name: Encrypted P2P Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install chromium

    - name: Build encrypted service
      run: |
        cd go-nostr-service
        go mod download
        go build -o trust-diary-encrypted main-encrypted.go
        ls -la trust-diary-encrypted

    - name: Run encrypted P2P tests
      run: |
        npx playwright test tests/encrypted-p2p.spec.ts --reporter=html

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-screenshots
        path: test-results/
        retention-days: 30